
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Panel.java
 *
 * Created on Aug 15, 2014, 12:22:20 PM
 */
/**
 *
 * @author Dany
 */
public class Panel extends javax.swing.JFrame {
    private Box[][] grid = new Box[4][4];
    
    /** Creates new form Panel */
    public Panel() {
        initComponents();
        
        JPanel pane = (JPanel) getContentPane();
        
        pane.setBorder(new EmptyBorder(10, 10, 10, 10));
        pane.setBackground(new Color(187, 173, 160));
        
        GridLayout l = (GridLayout) pane.getLayout();
        l.setHgap(10);
        l.setVgap(10);
        setSize(600, 600);
        
        for(int i=0; i<4; ++i){
            for(int j=0; j<4; ++j){
                Box b = new Box();
                b.setValue((int) Math.pow(2, 4*i + j));
                
                grid[i][j] = b;
                add(b);
            }
        }        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 4));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Panel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
